/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vulchivivek' at '9/22/17 12:49 PM' with Gradle 2.14.1
 *
 * @author vulchivivek, @date 9/22/17 12:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
